baseurl      = "noleto.tech"
title        = "Ivan Noleto"
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
theme        = "hello-friend-ng"
paginate     = 10
enableEmoji  = true


[permalinks]
  posts = "/posts/:title/"

[author]
  name = "Ivan Noleto"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "Desenvolvedor backend - Python | Golang"

  disableReadOtherPosts = false

  enableSharingButtons = true

  [params.footer]
    rss = true
    author = true
    trademark = true

  [params.portrait]
    path     = "https://avatars.githubusercontent.com/u/7867372"

  [[params.social]]
  name = "github"
  url = "https://github.com/balaios"

  [[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ivan-noleto/"

  [[params.social]]
  name = "email"
  url = "mailto:ivannoleto@hotmail.com"

  [menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"